name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    environment: ericfecteau.ca
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Zola Build
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          BUILD_ONLY: true

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: ericfecteau.ca
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Zola Build
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          BUILD_ONLY: true

      - name: Deploy to website
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          state-name: ../.ftp-deploy-sync-state.json