name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Zola Build
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          BUILD_ONLY: true